---
abstract: 'Mozilla Persona server implementation'
author:
  - 'Mark Overmeer'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mozilla-Persona
no_index:
  directory:
    - t
    - inc
requires:
  Apache::Htpasswd: 1.9
  CGI: 0
  CGI::Session: 0
  Crypt::OpenSSL::Bignum: 0
  Crypt::OpenSSL::RSA: 0
  Digest: 0
  File::Basename: 0
  File::Slurp: 0
  File::Spec: 0
  Getopt::Long: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  List::Util: 0
  Log::Report: 0
  MIME::Base64: 3.11
  Mail::ExpandAliases: 0
  Mail::IMAPTalk: 0
  Term::ReadPassword: 0.11
  Test::More: 0
  Time::HiRes: 0
  URI: 0
version: 0.12
